export const en = {
  // Szyna kanalow
  kanaly: 'Channels',
  przypnijSzyne: 'Pin the sidebar',
  odepnijSzyne: 'Unpin the sidebar',
  ustawienia: 'Settings',
  dodajKonto: 'Add account',
  brakKont: 'No accounts',

  // Listwa stanu
  makra: 'Macros',
  makraZeSkrotem: 'Macros (Ctrl+;)',
  ukryjKomunikat: 'Dismiss message',
  wybor: 'select',
  wstaw: 'insert',
  zamknijSkrot: 'close',
  nieprzeczytane: { one: '{n} new', other: '{n} new' },
  nieprzeczytaneSuma: { one: '{n} unread', other: '{n} unread' },
  brakNowych: 'no new',
  wszystkoPrzeczytane: 'all read',

  // Okno konta
  edycjaKonta: 'Edit account',
  nazwa: 'Name',
  platforma: 'Platform',
  kolorKanalu: 'Channel colour',
  anuluj: 'Cancel',
  zapisz: 'Save',

  // Ustawienia
  konta: 'Accounts',
  kolejnoscPodpowiedz: 'The order on this list is the order of the channels.',
  jezyk: 'Language',
  zamknij: 'Close',
  brakKontPodpowiedz: 'No accounts yet — click "Add account".',
  edytuj: 'Edit',
  usun: 'Remove',
  edytujKonto: 'Edit {nazwa}',
  usunKontoTytul: 'Remove {nazwa}',
  przesunWGore: 'Move {nazwa} up',
  przesunWDol: 'Move {nazwa} down',

  // Usuwanie konta
  usunacKonto: 'Remove this account?',
  kontoZniknie: '"{nazwa}" will disappear from the channel rail.',
  ostrzezenieUsuniecia: 'Removing an account also deletes its sign-in. Adding it back needs a new QR code.',
  usunKontoPrzycisk: 'Remove account',

  // Makra
  wstawDo: 'insert into',
  szukajMakro: 'Search by name, content or tag',
  brakMakr: 'No macros yet — click "New macro".',
  nicNiePasuje: 'Nothing matches "{fraza}". Try another phrase, or create a new macro.',
  noweMakro: 'New macro',
  makro: 'Macro',
  edycjaMakra: 'Edit macro',
  edytujMakro: 'Edit {nazwa}',
  usunMakroTytul: 'Remove {nazwa}',
  usunacMakro: 'Remove this macro?',
  usunMakroPytanie: '"{nazwa}" will disappear from the list.',
  usunMakroZZalacznikami: '"{nazwa}" will disappear along with its attachments ({liczba}).',
  usunMakroPrzycisk: 'Remove macro',
  etykietaMakra: '{nazwa}  ({liczba} att.)',

  // Edytor makra
  tresc: 'Content',
  pogrubienie: 'Bold',
  kursywa: 'Italic',
  przekreslenie: 'Strikethrough',
  lista: 'Bulleted list',
  numeracja: 'Numbered list',
  cytat: 'Quote',
  podgladWhatsApp: 'WhatsApp preview',
  zalaczniki: 'Attachments',
  dodajZalacznik: 'Add attachment',
  zdejmij: 'Remove',
  zdejmijPlik: 'Remove {nazwa}',
  magazynPodpowiedz: 'The file is copied into the app storage — you no longer need the original.',
  zapiszMakro: 'Save macro',
  brak: 'none',

  // Komunikaty
  komunikatBrakKonta: 'Nowhere to insert — add an account first, then open a conversation in it.',
  komunikatBrakMakra: 'That macro is no longer on the list.',
  komunikatPusteMakro: 'This macro has neither content nor an attachment — there is nothing to insert.',
  komunikatWstawianieNieudane: 'Could not insert the macro.',
  komunikatWstawiono: 'Inserted "{makro}" into {konto}. Pressing Enter is up to you.',
  komunikatKonta: 'the account',
  komunikatBrakujaZalaczniki: 'Attachments missing from storage: {lista}. The text was inserted anyway.',
  komunikatZalacznikBlad: 'Could not add the attachment: {blad}',
  komunikatWczytanieKont: 'Could not load the accounts: {blad}',

  // Walidacja — teksty dla kodow zwracanych przez proces glowny
  walidacjaId: 'the id must match acc-[a-z0-9-]+',
  walidacjaNazwa: 'the name is required',
  walidacjaPlatforma: 'unknown platform: {platforma}',
  walidacjaUrl: 'the address must start with https://',
  walidacjaKolor: 'the colour must use the #rrggbb format',
  walidacjaBrakKonta: 'no such account',
  walidacjaBrakMakra: 'no such macro',
}
