export const pl = {
  // Szyna kanalow
  kanaly: 'Kanały',
  przypnijSzyne: 'Przypnij panel',
  odepnijSzyne: 'Odepnij panel',
  ustawienia: 'Ustawienia',
  dodajKonto: 'Dodaj konto',
  brakKont: 'Brak kont',

  // Listwa stanu
  makra: 'Makra',
  makraZeSkrotem: 'Makra (Ctrl+;)',
  ukryjKomunikat: 'Ukryj komunikat',
  wybor: 'wybór',
  wstaw: 'wstaw',
  zamknijSkrot: 'zamknij',
  nieprzeczytane: { one: '{n} nowa', few: '{n} nowe', many: '{n} nowych', other: '{n} nowych' },
  nieprzeczytaneSuma: { one: '{n} nieprzeczytana', few: '{n} nieprzeczytane', many: '{n} nieprzeczytanych', other: '{n} nieprzeczytanych' },
  brakNowych: 'brak nowych',
  wszystkoPrzeczytane: 'wszystko przeczytane',

  // Okno konta
  edycjaKonta: 'Edycja konta',
  nazwa: 'Nazwa',
  platforma: 'Platforma',
  kolorKanalu: 'Kolor kanału',
  anuluj: 'Anuluj',
  zapisz: 'Zapisz',

  // Ustawienia
  konta: 'Konta',
  kolejnoscPodpowiedz: 'Kolejność na liście jest kolejnością kanałów.',
  jezyk: 'Język',
  zamknij: 'Zamknij',
  brakKontPodpowiedz: 'Brak kont — kliknij „Dodaj konto".',
  edytuj: 'Edytuj',
  usun: 'Usuń',
  edytujKonto: 'Edytuj {nazwa}',
  usunKontoTytul: 'Usuń {nazwa}',
  przesunWGore: 'Przesuń {nazwa} w górę',
  przesunWDol: 'Przesuń {nazwa} w dół',

  // Usuwanie konta
  usunacKonto: 'Usunąć to konto?',
  kontoZniknie: '„{nazwa}" zniknie z szyny kanałów.',
  ostrzezenieUsuniecia: 'Usunięcie konta kasuje też zalogowanie. Ponowne dodanie wymaga nowego kodu QR.',
  usunKontoPrzycisk: 'Usuń konto',

  // Makra
  wstawDo: 'wstaw do',
  szukajMakro: 'Szukaj po nazwie, treści lub tagu',
  brakMakr: 'Brak makr — kliknij „Nowe makro".',
  nicNiePasuje: 'Nic nie pasuje do „{fraza}". Zmień frazę albo utwórz nowe makro.',
  noweMakro: 'Nowe makro',
  makro: 'Makro',
  edycjaMakra: 'Edycja makra',
  edytujMakro: 'Edytuj {nazwa}',
  usunMakroTytul: 'Usuń {nazwa}',
  usunacMakro: 'Usunąć to makro?',
  usunMakroPytanie: '„{nazwa}" zniknie z listy.',
  usunMakroZZalacznikami: '„{nazwa}" zniknie razem z załącznikami ({liczba}).',
  usunMakroPrzycisk: 'Usuń makro',
  etykietaMakra: '{nazwa}  ({liczba} zał.)',

  // Edytor makra
  tresc: 'Treść',
  pogrubienie: 'Pogrubienie',
  kursywa: 'Kursywa',
  przekreslenie: 'Przekreślenie',
  lista: 'Lista punktowana',
  numeracja: 'Numeracja',
  cytat: 'Cytat',
  podgladWhatsApp: 'Podgląd w WhatsAppie',
  zalaczniki: 'Załączniki',
  dodajZalacznik: 'Dodaj załącznik',
  zdejmij: 'Zdejmij',
  zdejmijPlik: 'Zdejmij {nazwa}',
  magazynPodpowiedz: 'Plik trafia do magazynu aplikacji — oryginał przestaje być potrzebny.',
  zapiszMakro: 'Zapisz makro',
  brak: 'brak',

  // Komunikaty
  komunikatBrakKonta: 'Nie ma dokąd wstawić — najpierw dodaj konto i otwórz w nim rozmowę.',
  komunikatBrakMakra: 'Tego makra już nie ma na liście.',
  komunikatPusteMakro: 'To makro nie ma ani treści, ani załącznika — nie ma czego wstawić.',
  komunikatWstawianieNieudane: 'Nie udało się wstawić makra.',
  komunikatWstawiono: 'Wstawiono „{makro}" do {konto}. Enter należy do Ciebie.',
  komunikatKonta: 'konta',
  komunikatBrakujaZalaczniki: 'Brakuje załączników w magazynie: {lista}. Tekst został wstawiony.',
  komunikatZalacznikBlad: 'Nie można dodać załącznika: {blad}',
  komunikatWczytanieKont: 'Nie udało się wczytać kont: {blad}',

  // Walidacja — teksty dla kodow zwracanych przez proces glowny
  walidacjaId: 'id musi pasować do acc-[a-z0-9-]+',
  walidacjaNazwa: 'nazwa jest wymagana',
  walidacjaPlatforma: 'nieznana platforma: {platforma}',
  walidacjaUrl: 'adres musi zaczynać się od https://',
  walidacjaKolor: 'kolor musi być w formacie #rrggbb',
  walidacjaBrakKonta: 'nie ma takiego konta',
  walidacjaBrakMakra: 'nie ma takiego makra',
}
