// The preload of a sandboxed renderer must be CommonJS — Electron does not load ESM here.
const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('msgHub', {
  listAccounts: () => ipcRenderer.invoke('accounts:list'),
  addAccount: (data) => ipcRenderer.invoke('accounts:add', data),
  removeAccount: (accountId) => ipcRenderer.invoke('accounts:remove', accountId),
  unusedColor: () => ipcRenderer.invoke('accounts:unused-color'),
  updateAccount: (accountId, changes) => ipcRenderer.invoke('accounts:update', accountId, changes),
  moveAccount: (accountId, offset) => ipcRenderer.invoke('accounts:move', accountId, offset),
  switchAccount: (accountId) => ipcRenderer.invoke('accounts:switch', accountId),
  setViewsVisible: (visible) => ipcRenderer.invoke('views:visibility', visible),
  getCloseToTray: () => ipcRenderer.invoke('closeToTray:get'),
  setCloseToTray: (enabled) => ipcRenderer.invoke('closeToTray:set', enabled),
  downloadSettings: () => ipcRenderer.invoke('downloads:settings'),
  showDownload: (downloadId) => ipcRenderer.invoke('downloads:show', downloadId),
  setDownloadSettings: (changes) => ipcRenderer.invoke('downloads:settings-set', changes),
  pickDownloadDir: () => ipcRenderer.invoke('downloads:pick-dir'),
  getLanguage: () => ipcRenderer.invoke('language:get'),
  setLanguage: (code) => ipcRenderer.invoke('language:set', code),
  railState: () => ipcRenderer.invoke('rail:state'),
  hoverRail: (hovered, pointerStillInside) => ipcRenderer.invoke('rail:hover', hovered, pointerStillInside),
  pinRail: (pinned) => ipcRenderer.invoke('rail:pin', pinned),
  onRailChange: (listener) => ipcRenderer.on('rail:changed', (_event, state) => listener(state)),
  onRailRecheck: (listener) => ipcRenderer.on('rail:recheck', () => listener()),
  onMessage: (listener) => ipcRenderer.on('message:show', (_event, payload) => listener(payload)),
  reloadAccount: (accountId) => ipcRenderer.invoke('accounts:reload', accountId),
  onUnread: (listener) => ipcRenderer.on('unread:changed', (_event, data) => listener(data)),
  setOverlay: (image) => ipcRenderer.invoke('unread:overlay', image),
  onOpenMacros: (listener) => ipcRenderer.on('macros:open', () => listener()),
  onSelectAccount: (listener) => ipcRenderer.on('accounts:select', (_event, index) => listener(index)),
  onSelectAccountId: (listener) => ipcRenderer.on('accounts:select-id', (_event, accountId) => listener(accountId)),
  listMacros: (phrase) => ipcRenderer.invoke('macros:list', phrase),
  saveMacro: (macro) => ipcRenderer.invoke('macros:save', macro),
  removeMacro: (macroId) => ipcRenderer.invoke('macros:remove', macroId),
  insertMacro: (macroId, values) => ipcRenderer.invoke('macros:insert', macroId, values),
  pickFile: () => ipcRenderer.invoke('files:pick'),
})
